### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by dotmagic** [gehaxelt/Bash-INWX-DynDNS#11]
I do use Archlinux and get a error 

LANG=C ./dnsupdate.sh 
Sat Dec 31 21:38:49 UTC 2016 | Updating IPv4...
sed: -e expression #1, char 154: unknown option to `s'
Sat Dec 31 21:38:49 UTC 2016 | Something went wrong updating the IPv4 address. Check the configuration and make sure you're not using Two-Factor-Authentication.

**Comment by Strubbl** [comment]
Same here, it is because variable $NEWIPv4 contains the log message plus the new ip address, e.g.

```
Tue Jan  3 19:23:09 UTC 2017 | No IPv4 pool (v4.pool file) found. Using https://ip4.nnev.de/
8.2.8.52
```

if you comment the line https://github.com/gehaxelt/Bash-INWX-DynDNS/blob/master/dnsupdate.sh#L15 it should work again

**Comment by gehaxelt** [comment]
Hi,
I pushed a fix for the issue by commenting out the log message as @Strubbl suggested. Thanks! 

I guess that setting `SILENT=true` would also fix the issue.
