### ISSUE TITLE
Updating problem

### ISSUE THREAD

**Issue by ChristianKrausse** [gehaxelt/Bash-INWX-DynDNS#16]
Has there be something changed at INWX? 

After reviewing my logs, the "Something went wrong updating the IPv4 address" came more frequent in the last time. At "Mi 13. Sep 12:30:18 UTC 2017" I had the last succesful update to INWX.  
The API URL from inwx.de seems to be up "https://api.domrobot.com/xmlrpc/" 

Mi 13. Sep 12:25:14 UTC 2017 | Something went wrong updating the IPv4 address. Check the configuration and make sure you're not using Two-Factor-Authentication.
Mi 13. Sep 12:30:03 UTC 2017 | Updating IPv4...
Mi 13. Sep 12:30:18 UTC 2017 | Updated IPv4: (empty) --> 

Edit: It seems to be https://ip4.nnev.de/ is currently down, enabling the v4.pool and v6.pool seem to fix at least the ipv4 updating problem. Updating the v6 IP is still failing over the pool variant.

Edit2: fixed the typo in the IPv6 Pool checking section.

**Comment by gehaxelt** [comment]
Thanks for the PR #17 

I'm closing this now.
