### ISSUE TITLE
Invalid ident.me SSL certificate

### ISSUE THREAD

**Issue by christoph-bessei** [gehaxelt/Bash-INWX-DynDNS#19]
The SSL certificate for ip4.ident.me and ip6.ident.me is invalid.
Seems like the new domains are v4.ident.me and v6.ident.me, both have a valid certificate.

**Comment by gehaxelt** [comment]
Hi @christoph-bessei 
are you sure that you are using the newest `v4.pool.sample` or `v6.pool.sample`  or reported the correct domains? 

There's neither `ip4.ident.me` nor `ipv6.ident.me`, but `v4.ident.me` and `v6.ident.me` in the files. I don't see any SSL errors for the latter ones. 

Kind regards,
Sebastian

**Comment by christoph-bessei** [comment]
Sorry, I should have been more specific.
I'm not using the pool feature, but the entries inside dnsupdate.sh:
https://github.com/gehaxelt/Bash-INWX-DynDNS/blob/29e1f088eae20627e333aa7a1a34545a3035a6f3/dnsupdate.sh#L16
https://github.com/gehaxelt/Bash-INWX-DynDNS/blob/29e1f088eae20627e333aa7a1a34545a3035a6f3/dnsupdate.sh#L36

**Comment by gehaxelt** [comment]
Hi @christoph-bessei 
sorry for the delay response... I created a PR #20 that should replace the old subdomains with the newer, correct ones. 

Could you please check if the PR fixes the issue so that I can merge it? 

Thanks for reporting the bug,
Sebastian

**Comment by christoph-bessei** [comment]
The PR works fine on 16.04, thanks for the quick fix!
