### ISSUE TITLE
curlmyip.com does not work

### ISSUE THREAD

**Issue by karlsonvomdach** [gehaxelt/Bash-INWX-DynDNS#4]
Hey gehaxelt,

your inwx solution worked nicely for me until recently. 
curlmyip.com does not work anymore. 
May you update your code with an alternative?

best,
karlson

**Comment by freesbie42** [comment]
use .net for ipv4

**Comment by joker234** [comment]
I use ip4.nnev.de and ip6.nnev.de as replacement.

**Comment by gehaxelt** [comment]
@karlsonvomdach 
Hi, thanks for bringing that up!

@joker234 
Would you mind creating a PR? 
I don't have any stable internet at the moment, so I can't push my own fix in the next couple of days. 

Kind regards,
gehaxelt
