### ISSUE TITLE
Skript schlägt fehl wenn ip4.nnev.de oder ip6.nnev.de down ist

### ISSUE THREAD

**Issue by JonasGroeger** [gehaxelt/Bash-INWX-DynDNS#6]
Das Skript macht keine Prüfung der Ausgabe von `curl -s ip4.nnev.de` oder `curl -s ip6.nnev.de`. Idealerweise sollte man hier einen Pool kontaktieren.

**Comment by gehaxelt** [comment]
Hi @JonasGroeger 
hast du irgendwelche Pools im Kopf, die man nutzen könnte?

**Comment by JonasGroeger** [comment]
Einmal `ip address api` bei google eingeben.

**Comment by joker234** [comment]
ip.nnev.de wird vom [NoName e.V.](https://www.noname-ev.de) betrieben. Ich hatte das damals in das Skript eingebaut weil die Alte URL nicht mehr betrieben wird und weil der Service vom NoName nur die IP-Adresse und sonst nichts zurück gibt, was einfacher zu skripten war. Wenn jemand einen echten Pool kennt wäre das natürlich viel sinnvoller.

Was aber auch passieren sollte, ist dass das Skript sinnvolle Fehlermeldungen gibt wenn `curl -s …` nicht funktioniert. Das kann dem besten pool passieren.

**Comment by JonasGroeger** [comment]
@joker234 Wenn man einen Pool nimmt dann ist es vmtl. besser wenn man das ganze evtl. in Python und nicht in Bash schreibt. Sonst wird das hässlich.

**Comment by gehaxelt** [comment]
Ah, jetzt verstehe ich erst, was ihr meint: Einen Pool an verschiedenen IP-APIs, welche man abfrägt, falls ein Dienst ausfällt? 

Idee:
Man baut ein Array an IP-APIs und loop darüber solange eine API etwas zurückliefert? (Kein Fehler durch curl schmeißt)?

Tendenziell würde ich dann probieren, sowas in Bash zu machen, damit man nicht noch eine weitere Dependency einbaut. Möglicherweise kann man dieses kleine "Tool" auch einfach direkt in ein kleines Python-script porten, welches dann stand-alone laufen könnte?

**Comment by JonasGroeger** [comment]
genau

**Comment by Strubbl** [comment]
Man könnte für die Bash Lösung eine Datei mit den IP-APIs anlegen mit einer IP-Api pro Zeile und die zeilenweise einlesen und auswerten

**Comment by JonasGroeger** [comment]
In meinem Fork ist ein failover mit Validierung: https://github.com/JonasGroeger/inwx.de-ddns

**Comment by gehaxelt** [comment]
@JonasGroeger Dein Fork sieht doch interessant und gut aus. Magst du einen PR erstellen?

**Comment by JonasGroeger** [comment]
@gehaxelt Ich hab so ziemlich alles umgebaut :) Daher lasse ich das mal bei mir. Kann ja auch jeder verwenden.

**Comment by gehaxelt** [comment]
Okay, dann werde ich mir einfach die passenden Stellen abschauen und übernehmen...
