### ISSUE TITLE
Die Ausgabe von curl wird nicht geprüft

### ISSUE THREAD

**Issue by JonasGroeger** [gehaxelt/Bash-INWX-DynDNS#8]
Die Ausgabe des curl (POST) Befehls wird nicht geprüft. Falls `https://api.domrobot.com/xmlrpc/` down ist, bekommt man keinen Fehler. Auch wenn man eine falsche Konfiguration angibt.

Idealerweise sollte dann ein nicht-null Fehlercode zurückgegeben werden.

**Comment by gehaxelt** [comment]
Hey, 
meinst du, [sowas hier](https://superuser.com/questions/742408/how-to-stop-shell-script-if-curl-failed) reicht aus. Das würde zumindest den "down"-Fall abfangen. Für den zweiten Fall (falsche Konfig) könnte man einfach die `update.log` nach einem Fehler (?) greppen und dann returnen, oder?

**Comment by JonasGroeger** [comment]
Ich hab das eben mal geschrieben. Sowas meine ich.

```
#!/bin/bash

V4_POOL=(
    "https://ip4.nnev.de/"
    "http://v4.ident.me/"
    "https://ipv4.icanhazip.com"
    "https://v4.ifconfig.co/"
    "https://ipv4.wtfismyip.com/text"
)

V6_POOL=(
    "https://ip6.nnev.de/"
    "http://v6.ident.me/"
    "https://ipv6.icanhazip.com"
    "https://v6.ifconfig.co/"
    "https://ipv6.wtfismyip.com/text"
)

function v4() {
    for V4_API in "${V4_POOL[@]}"; do
        MAYBE_V4_ADDR=$(curl -s "$V4_API")
        if [[ $MAYBE_V4_ADDR =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "$MAYBE_V4_ADDR"
            return 0
        fi

        continue
    done

    return 1
}

function v6() {
    for V6_API in "${V6_POOL[@]}"; do
        MAYBE_V6_ADDR=$(curl -s "$V6_API")
        if [[ $MAYBE_V6_ADDR == *":"* ]]; then
            echo "$MAYBE_V6_ADDR"
            return 0
        fi
        continue
    done
    return 1
}

```
